### ISSUE TITLE
Set up int for all numeric json values

### ISSUE THREAD

**Issue by techyrajeev** [graphql-compose/graphql-compose-json#6]
From example code -

```const restApiResponse = {
  name: 'Anakin Skywalker',
  birth_year: '41.9BBY',
  starships: [
    'https://swapi.co/api/starships/59/',
    'https://swapi.co/api/starships/65/',
    'https://swapi.co/api/starships/39/',
  ],
  mass: () => 'Int!', // by default JSON numbers coerced to Float, here we set up Int
};
```
Here mass is set to `int` explicitly. But how can we set all numeric values present in json to `int` directly without specifying for each field?

**Comment by nodkz** [comment]
There is no such way. You must define for every field manually with this lib.

BUT this lib is very tiny
Take a look at https://github.com/graphql-compose/graphql-compose-json/blob/master/src/ObjectParser.js

You may rewrite the code in your app and import core package [graphql-compose](https://github.com/graphql-compose/graphql-compose) 😉
