### ISSUE TITLE
Shallow?

### ISSUE THREAD

**Issue by azat-co** [graphql-compose/graphql-compose-json#7]
Is this a shallow converter? I'm always getting JSON on nested types. It'll be nice to add some if/else in recursion to make this library to go deep.

**Comment by nodkz** [comment]
Its strange.
Should also create sub types.
See this lines https://github.com/graphql-compose/graphql-compose-json/blob/8947d87db09268e324735951057339e9869cdabb/src/ObjectParser.js#L43

Can you provide a test case? Or even make PR (хватит книжки писать - сделай ПР, почему на holyjs не был)?

Right now I'm in Moscow. Will be at home via several days. But your changes may publish from mobile phone. 🤘

**Comment by nodkz** [comment]
@azat-co just added a test case for checking nested objects. And it properly creates Type for nested object.
https://github.com/graphql-compose/graphql-compose-json/blob/041e4ef850eb6d1b7318cf1d96e13872ce45535b/src/__tests__/composeWithJson-test.js#L156-L171

Maybe you have another case which does not work for you?

**Comment by azat-co** [comment]
У меня был JSON for nested types. Я могу посмотреть и про тестировать ещею

**Comment by azat-co** [comment]
По моему это возникало на 2 или 3 уровне вложенности 

Еще не могу сделать строку из типа

```js
const composeWithJson = require('graphql-compose-json').default;
const { print } = require('graphql/language/printer');
const {parse} = require('graphql');


const restApiResponse = require('./JobSearchResponseIndexResultsPage.gql')

const JobSearchResponse = composeWithJson('JobSearchResponse', restApiResponse);
const JobSearchResponseGQLType = JobSearchResponse.getType();
// console.log(print(parse(JobSearchResponse)));
```

Это как?
